### ISSUE TITLE
Access Violation alla pressione di Setup della Stampante

### ISSUE THREAD

**Issue by thej4ck** [EtheaDev/FExplorer#1]
![image](https://user-images.githubusercontent.com/5577620/114834957-5e415e00-9dd1-11eb-877e-cb8477efe11d.png)
alla pressione di "Setup della stampante"

strano.
Ciao

**Comment by carloBarazzetta** [comment]
Non è strano quando si finisce a mezzanotte di integrare la preview di stampa ;-)
A parte gli scherzi indicami bene i passaggi che hai fatto: sei dentro il "visualizzatore/editor"?

**Comment by thej4ck** [comment]
Grandissimi lo stesso!

**Comment by carloBarazzetta** [comment]
Certo che se premi sull'anteprima di stampa senza aver caricato nessun file è il minimo che ti possa capitare un bel "AV" in faccia 
:-D
