### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by viktheboss** [EtheaDev/FExplorer#6]
Sarebbe molto comodo avere l'opzione in oggetto.
Grazie

**Comment by carloBarazzetta** [comment]
Nell'editor?

**Comment by viktheboss** [comment]
Nel visualizzatore delle FE!!! Sarebbe molto più fruibile!!! :-)

**Comment by carloBarazzetta** [comment]
Il drag-drop è stato implementato nella 1.5.0

**Comment by viktheboss** [comment]
Fantastico, scarico subito l'aggiornamento!!
Grazie mille

Vittorio Antonello
