### ISSUE TITLE
Anteprima Explorer  2.3.0.0 - Layout errato per mancanza codice articolo

### ISSUE THREAD

**Issue by webgaldom** [EtheaDev/FExplorer#9]
Nell'ultima versione di FExplorer - l'Anteprima della fattura xml in Esplora risorse presenta un layout errato della parte centrale nel caso manchi il codice articolo. Con il codice articolo tutto viene renderizzato bene.

![image](https://github.com/EtheaDev/FExplorer/assets/109237948/52042277-7298-4209-8c91-47778f88ebf3)

Segnalo inoltre che il foglio di stile Assoinvoice è stato aggiornato a marzo 2024.

Complimenti come sempre per l'ottimo lavoro.

**Comment by carloBarazzetta** [comment]
> Nell'ultima versione di FExplorer - l'Anteprima della fattura xml in Esplora risorse presenta un layout errato della parte centrale nel caso manchi il codice articolo. Con il codice articolo tutto viene renderizzato bene.

Potresti allegare l'esempio del file xml senza codice articolo, in modo da poter fare i test?

**Comment by carloBarazzetta** [comment]
Fixato nella Versione 2.3.0

**Comment by webgaldom** [comment]
> Fixato nella Versione 2.3.0

Grazie di tutto e scusami se non sono riuscito a mandarti un file xml, ma erano tutti renderizzati in quel modo. Complimenti per l'ottimo lavoro!

**Comment by webgaldom** [comment]
Scusami Carlo, ho aggiornato alla versione 2.3.0 ma non è cambiato nulla per il bug in questione.
ti ho allegato un file xml senza codice articolo.

[IT01234567890_00797.zip](https://github.com/EtheaDev/FExplorer/files/15496919/IT01234567890_00797.zip)

**Comment by carloBarazzetta** [comment]
Ma hai provato ad andare in "impostazioni" e scegliere Stile anteprima fattura: "Custom": è una versione migliorata (secondo me) di AssoSoftware.

**Comment by carloBarazzetta** [comment]
Comunque ho visto il problema, lo fa sopratutto con il foglio di stile AssoSoftware standard: l'ho aggiornato ma evidentemente qualcosa non ha funzionato... faccio una verifica

**Comment by webgaldom** [comment]
In effetti non ho provato.
Fra poco ti aggiorno

Il gio 30 mag 2024, 15:01 Carlo Barazzetta ***@***.***> ha
scritto:
